Repository jenkinsci/credentials-binding-plugin, pull requests merged in 2024-01, with the labels that each got.

#286 Suppress warnings for spotbugs 4.8.3
  pom.xml
  src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding.java
Labels: dependencies

#287 Fixes invalid context expectation in test
  pom.xml
  src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Labels: developer

#288 Improved usage of `MissingContextVariableException`
  pom.xml
  src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
  src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Labels: chore
